# Telegraf configuration for Mosquitto public broker and InfluxDB output
telegraf:
  mqtt:
    broker_url: "tcp://test.mosquitto.org:1883"
    topics: ["CamDT/DC1/IfM/#"]
  influxdb:
    url: "http://ds-influxdb.elasticdt:8086"
    token: "super-secret-token"
    org: "camdt"
    bucket: "default"
