releases:
  - name: traefik
    namespace: traefik
    chart: oci://ghcr.io/traefik/helm/traefik
    version: "31.0.0"
    values:
      - ./Infrastructure/traefik.yaml

  - name: ui-homepage
    namespace: elasticdt
    chart: ./Services/ui/homepage
    needs:
      - traefik/traefik
    values:
      - container:
          image: anandarup1987/cherrypy-webserver
          tag: latest
      - traefik:
          enabled: true
          hostName: localhost
          path: /

  - name: ds-influxdb
    namespace: elasticdt
    chart: ./Services/ds/influxdb
    needs:
      - traefik/traefik
    values:
      - admin:
          username: root
          password: password
          org: camdt
          bucket: default
          token: super-secret-token
      - traefik:
          enabled: true
          hostName: influxdb.localhost
          path: /

  - name: di-mqtt
    namespace: elasticdt
    chart: ./Services/di/sensor_mqtt
    needs:
      - traefik/traefik
      - elasticdt/ds-influxdb
    values:
      - telegraf:
          mqtt:
            broker_url: "tcp://test.mosquitto.org:1883"
            topics: ["CamDT/DC1/IfM/#"]
          influxdb:
            url: "http://ds-influxdb.elasticdt:8086"
            token: "super-secret-token"
            org: "camdt"
            bucket: "default"

  - name: ui-grafana
    namespace: elasticdt
    chart: ./Services/ui/grafana
    needs:
      - traefik/traefik
    values:
      - image:
          tag: "9.5.3"
      - config:
          org_name: "Main Org."
          org_role: "Viewer"
      - traefik:
          enabled: true
          hostName: grafana.localhost
  - name: di-inventory-management
    namespace: elasticdt
    chart: ./Services/di/inv_mgmt
    values:
      - container:
          image: anandarup1987/inventory_management
          tag: latest
      - service:
          port: 12122
          targetPort: 8000
      - traefik:
          enabled: true
          hostName: inventory.localhost
          path: /
  - name: ds-neo4j
    namespace: elasticdt
    chart: ./Services/ds/neo4j
    needs:
      - traefik/traefik
    values:
      - neo4j:
          password: password
      - traefik:
          enabled: true