container:
  image: ghcr.io/cam-digital-hospitals/ui-homepage
  tag: latest

service:
  type: ClusterIP
  port: 12121

# HTTPRoute Configuration for Traefik
traefik:
  enabled: true
  namespace: traefik  # Namespace of the traefik chart
  hostName: localhost
  path: /
  stripPrefix: false