replicas: 1

image:
  repository: grafana/grafana
  tag: "9.5.3"

config:
  root_url: http://localhost/grafana/
  serve_from_sub_path: true
  enforce_domain: false
  allow_embedding: true
  anonymous_enabled: true
  org_name: Main Org.
  org_role: Viewer
  hide_version: true
  device_limit: 5

# HTTPRoute Configuration for Traefik
traefik:
  enabled: true
  namespace: traefik  # Namespace of the traefik chart
  hostName: grafana.localhost
  path: /grafana
  stripPrefix: false

service:
  type: ClusterIP
  port: 3000
