apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-config
  labels:
    app: {{ .Release.Name }}-grafana
data:
  grafana.ini: |
    [server]
    root_url = {{ .Values.config.root_url }}
    serve_from_sub_path = {{ .Values.config.serve_from_sub_path }}
    enforce_domain = {{ .Values.config.enforce_domain }}
    [security]
    allow_embedding = {{ .Values.config.allow_embedding }}
    [auth]
    # disable_login_form = true
    [auth.anonymous]
    enabled = {{ .Values.config.anonymous_enabled }}
    org_name = {{ .Values.config.org_name }}
    org_role = {{ .Values.config.org_role }}
    hide_version = {{ .Values.config.hide_version }}
    device_limit = {{ .Values.config.device_limit }}
