apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    app: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | default "10Gi" }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName | default "standard" }}
  hostPath:
    path: {{ .Values.persistence.hostPath | default "/data/mysql_data/" }}
