replicaCount: 1

image:
  repository: influxdb
  tag: "2.7-alpine"
  pullPolicy: IfNotPresent

admin:
  enabled: true
  username: root
  password: password
  org: camdt
  bucket: default
  token: super-secret-token

authEnabled: true

persistence:
  enabled: true
  storageClass: standard
  accessModes:
    - ReadWriteOnce
  size: 10Gi

service:
  type: ClusterIP
  port: 8086

# HTTPRoute Configuration for Traefik
traefik:
  enabled: true
  namespace: traefik  # Namespace of the traefik chart
  hostName: influxdb.localhost
  path: /
  stripPrefix: false
