apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-telegraf-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: {{ .Release.Name }}-telegraf
