apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: elasticdt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: elasticdt-admin-binding
  namespace: elasticdt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin
  namespace: elasticdt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dtadmin
  name: dtadmin
  namespace: elasticdt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dtadmin
    spec:
      serviceAccountName: admin
      containers:
      - image: elasticdt/admin:0.1.0
        name: admin
        resources: {}
status: {}
