apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: elasticdt
  name: httproute-viewer
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get", "list", "watch"]
