{{- if .Values.traefik.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-web-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: {{ .Values.traefik.namespace }}
  hostnames:
  - {{ .Values.traefik.web.hostName }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.traefik.web.path }}
    backendRefs:
    - name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.portHTTP }}
{{- if .Values.traefik.web.stripPrefix }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: {{ .Release.Name }}-strip-prefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.traefik.web.path }}
{{- end }}
{{- end }}