{{- if .Values.traefik.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: {{ .Values.traefik.namespace }}
  hostnames:
  - {{ .Values.traefik.hostName }}
  rules:
  # Rule to redirect requests from the root path ("/") to "/grafana"
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: "http"
        path:
          type: "ReplacePrefixMatch"
          replacePrefixMatch: "/grafana"

  # Rule to handle requests to the "/grafana" path
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.traefik.path }}
    backendRefs:
    - name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.port }}
{{- if .Values.traefik.stripPrefix }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: {{ .Release.Name }}-strip-prefix
--- 
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-prefix
  namespace: {{ .Release.namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.traefik.path }}
{{- end }}
{{- end }}
