apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-influxdb
spec:
  selector:
    app: {{ .Release.Name }}-influxdb
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
  type: {{ .Values.service.type | default "ClusterIP" }}
